# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ubuntu/squid
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  # https://hub.docker.com/r/semaphoreui/semaphore/tags
  tag: "edge"

#strategy: {}
strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 1

# enable data on pvc
#pvc:
#  accessModes: "ReadWriteOnce"
#  storageClassName: "microk8s-hostpath"
# or data on tmp
tmp:
  medium: '' # Memory
  size: 1Gi

# --set "env.FOO=bar,env.TEST=true"
#env:
#  DATABASE_DRIVER: "bolt"
#  DATABASE_HOST: null
#  DATABASE_NAME: "semaphore"
#  DATABASE_PASSWORD: null
#  DATABASE_PATH: "/var/lib/semaphore/database.boltdb"
#  DATABASE_PORT: null
#  DATABASE_USERNAME: "semaphore"
env: {}

# envFrom:
#   configmaps:
#     BAR: foo
#     TEST: true
#   secrets:
#     FOO: "supersecret"
envFrom:
  configmaps: {}
  secrets: {}

volumeMountsPath:
  configmaps: /etc/squid/conf.d
  secrets: /etc/squid/secrets

# volumeMounts:
#   configmaps:
#     config.yaml: |
#       BAR: foo
#       TEST: true
#   secrets:
#     secrets.yaml: |
#       FOO: "supersecret"
volumeMounts:
  configmaps: {}
  secrets: {}

squid_config: |-
  http_port 3128
  coredump_dir /var/spool/squid
  refresh_pattern ^ftp:		1440	20%	10080
  refresh_pattern ^gopher:	1440	0%	1440
  refresh_pattern -i (/cgi-bin/|\?) 0	0%	0
  refresh_pattern \/(Packages|Sources)(|\.bz2|\.gz|\.xz)$ 0 0% 0 refresh-ims
  refresh_pattern \/Release(|\.gpg)$ 0 0% 0 refresh-ims
  refresh_pattern \/InRelease$ 0 0% 0 refresh-ims
  refresh_pattern \/(Translation-.*)(|\.bz2|\.gz|\.xz)$ 0 0% 0 refresh-ims
  refresh_pattern .		0	20%	4320
  logfile_rotate 0
  # disable pinger
  pinger_enable off
  # debug all
  # debug_options ALL,1 33,2
  #logformat squid_access %ts %>a %rm %>rd %>rP %rp %>Hs %<st %Ss %err_code
  #access_log daemon:/var/log/squid/access.log squid_access
  #
  # Default parent proxy (upstream)
  #cache_peer proxy.external parent 8080 0 no-query default
  # Default traffic redirection to the parent
  never_direct allow all

  # Allowed port ACLs
  acl SSL_ports port 443
  acl Safe_ports port 80		# http
  acl Safe_ports port 443		# https
  acl CONNECT method CONNECT

  # ACL sources
  acl localhost src 127.0.0.1/32
  acl localnet src 0.0.0.1-0.255.255.255	# RFC 1122 "this" network (LAN)
  acl localnet src 10.0.0.0/8		# RFC 1918 local private network (LAN)
  acl localnet src 100.64.0.0/10		# RFC 6598 shared address space (CGN)
  acl localnet src 169.254.0.0/16 	# RFC 3927 link-local (directly plugged) machines
  acl localnet src 172.16.0.0/12		# RFC 1918 local private network (LAN)
  acl localnet src 192.168.0.0/16		# RFC 1918 local private network (LAN)
  acl localnet src fc00::/7       	# RFC 4193 local private network range
  acl localnet src fe80::/10      	# RFC 4291 link-local (directly plugged) machines
  # === EXCLUDED zones from parent proxy (direct send) ===
  # IPs or ranges sent directly
  acl direct_ips dst 10.0.0.0/8
  # Domains NOT to send to the parent proxy
  acl direct_domains dstdomain .svc.cluster.local localhost

  # Enforce direct routes (without proxy)
  always_direct allow direct_ips
  always_direct allow direct_domains

  # === ALLOWED zones via parent proxy ===
  # Allowed sites only (everything else blocked)
  #acl allowed_sites dstdomain .google.fr .wikimedia.org
  # here on allow all URLs
  acl allowed_sites dstdomain .

  # --- HTTP Access Control ---
  # 1. Disallow everything except HTTP/HTTPS
  http_access deny !Safe_ports
  http_access deny CONNECT !SSL_ports
  # 2. Allow only validated destinations
  http_access allow allowed_sites
  # 3. Everything else is blocked
  http_access deny all
  #
  include /etc/squid/conf.d/*

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

livenessProbe:
  tcpSocket:
    port: 3128
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

#  httpGet:
#    path: /
#    port: squid
#  failureThreshold: 3
#  initialDelaySeconds: 30
#  periodSeconds: 10
#  timeoutSeconds: 5

readinessProbe:
  tcpSocket:
    port: 3128
#  httpGet:
#    path: /
#    port: squid
#  failureThreshold: 3
#  initialDelaySeconds: 30
#  periodSeconds: 10
#  successThreshold: 3
#  timeoutSeconds: 5

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000
  seccompProfile:
    type: "RuntimeDefault"

service:
  enabled: true
  type: ClusterIP
  port: 3128
  internalPort: 3128

ingress:
  enabled: false
#  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
  #      - path: /
  #        pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
#  limits:
#    cpu: 10m
#    memory: 128Mi
#  requests:
#    cpu: 100m
#    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

test:
  enabled: false

nodeSelector: {}

tolerations: []

affinity: {}
