apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "squid.fullname" . }}
  namespace: {{ include "squid.namespace" . | quote }}
  labels:
    {{- include "squid.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  {{- with .Values.strategy }}
  strategy:
    {{- toYaml . | trim | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "squid.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "squid.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.initContainers }}
      initContainers:
{{ toYaml .Values.initContainers | indent 8 }}
      {{- end }}
      serviceAccountName: {{ include "squid.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.dnsPolicy }}
      dnsPolicy: "{{ .Values.dnsPolicy }}"
      {{- end }}
      {{- if .Values.dnsConfig }}
      dnsConfig:
{{ toYaml .Values.dnsConfig | indent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: squid
              containerPort: {{ .Values.service.internalPort | default "3128" }}
              protocol: TCP
          livenessProbe:
#            exec:
#              command:
#                - /usr/sbin/squid
#                - -k
#                - parse
            {{- if .Values.livenessProbe }}
{{- toYaml .Values.livenessProbe | nindent 12 }}
            {{- end }}
          {{- if .Values.readinessProbe }}
          readinessProbe:
{{- toYaml .Values.readinessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.volumeMounts }}
          volumeMounts:
            - name: run
              mountPath: /run
            - name: var-log
              mountPath: /var/log/squid
            - name: squid-data-vol
              mountPath: /var/spool/squid
            - name: squid-config-vol
              mountPath: /etc/squid/squid.conf
              subPath: squid.conf
            {{- range $key, $val := .Values.volumeMounts.configmaps }}
            - name: {{  regexReplaceAll "[._]" $key "-" }}
              mountPath: {{ $.Values.volumeMountsPath.configmaps }}/{{ $key }}
              subPath: {{ $key }}
              readOnly: true
            {{- end }}
            {{- range $key, $val := .Values.volumeMounts.secrets }}
            - name: {{ $key }}
              mountPath: {{ $.Values.volumeMountsPath.secrets }}/{{ $key }}
              subPath: {{ $key }}
              readOnly: true
            {{- end }}
          {{- end }}
          {{- if .Values.envFrom }}
          {{- if or .Values.envFrom.configmaps .Values.envFrom.secrets }}
          envFrom:
            {{- if .Values.envFrom.configmaps }}
            - configMapRef:
                name: {{ template "squid.fullname" . }}
            {{- end }}
            {{- if .Values.envFrom.secrets }}
            - secretRef:
                name: {{ template "squid.fullname" . }}
            {{- end }}
          {{- end }}
          {{- end }}
          {{- with .Values.env }}
          env:
            {{- range $k, $v := . }}
            - name: {{ $k | quote}}
              value: {{ $v | quote }}
            {{- end }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: run
          emptyDir: {}
        - name: var-log
          emptyDir: {}
        - name: squid-data-vol
          {{- if .Values.pvc }}
          persistentVolumeClaim:
            claimName: {{ template "squid.fullname" . }}-data
          {{- else }}
          emptyDir:
            medium: "{{ .Values.tmp.medium }}"
            sizeLimit: "{{ .Values.tmp.size }}"
          {{- end }}
        - name: squid-config-vol
          configMap:
            name: {{ template "squid.fullname" . }}-config
            items:
            - key: squid.conf
              path: squid.conf
        {{- range $key, $val := .Values.volumeMounts.configmaps }}
        - name: {{  regexReplaceAll "[._]" $key "-" }}
          configMap:
            name: {{ template "squid.fullname" $ }}-vols
        {{- end }}
        {{- range $key, $val := .Values.volumeMounts.secrets }}
        - name: {{ $key }}
          secret:
            secretName: {{ template "squid.fullname" $ }}-vols
        {{- end }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
