apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ template "squid.name" . }}"
  labels:
    app: "{{ template "squid.name" . }}"
spec:
  selector:
    matchLabels:
      app: "{{ template "squid.name" . }}"
  replicas: {{ .Values.replicas }}
  strategy:
{{ toYaml .Values.strategy | trim | indent 4 }}
  template:
    metadata:
      name: "{{ template "squid.name" . }}"
      labels:
        app: "{{ template "squid.name" . }}"
{{- if .Values.labels }}
{{ toYaml .Values.labels | indent 8 }}
{{- end }}
{{- if .Values.annotations }}
      annotations:
{{ toYaml .Values.annotations | indent 8 }}
{{- end }}
    spec:
      {{- if .Values.schedulerName }}
      schedulerName: "{{ .Values.schedulerName }}"
      {{- end }}
      securityContext:
{{ toYaml .Values.podSecurityContext | indent 8 }}
      {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.nodeAffinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriod }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}
      {{- end }}
      {{- if .Values.initContainers }}
      initContainers:
{{ toYaml .Values.initContainers | indent 8 }}
      {{- end }}
      {{- if .Values.dnsPolicy }}
      dnsPolicy: "{{ .Values.dnsPolicy }}"
      {{- end }}
      {{- if .Values.dnsConfig }}
      dnsConfig:
{{ toYaml .Values.dnsConfig | indent 8 }}
      {{- end }}
      containers:
        - name: "{{ template "squid.name" . }}"
          image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.imagePullPolicy }}"
          ports:
            - containerPort: 3128
              name: squid
              protocol: TCP
          livenessProbe:
            exec:
              command:
                - /usr/sbin/squid
                - -k
                - parse
{{ toYaml .Values.livenessProbe | indent 12 }}
          readinessProbe:
            tcpSocket:
              port: 3128
{{ toYaml .Values.readinessProbe | indent 12 }}
          volumeMounts:
            - mountPath: /etc/squid/conf.d
              name: squid-config-volume
              readOnly: false
            - mountPath: /var/log/squid
              name: tmp
              subPath: squid-log
            - mountPath: /var/spool/squid
              name: tmp
              subPath: squid-cache
            {{- if .Values.volumeMounts }}
{{ toYaml .Values.volumeMounts | indent 12 }}
            {{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
      volumes:
        - name: tmp
          emptyDir:
            medium: "{{ .Values.tmp.medium }}"
            sizeLimit: "{{ .Values.tmp.size }}"
        - name: squid-config-volume
          configMap:
            name: "{{ template "squid.name" . }}-config"
        {{- if .Values.volumes }}
{{ toYaml .Values.volumes | indent 8 }}
        {{- end }}
