{{- if .Values.envFrom }}
{{- if .Values.envFrom.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "helmproj.fullname" . }}
  namespace: {{ include "helmproj.namespace" . | quote }}
data:
  {{- range $key, $value := .Values.envFrom.secrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}
{{- end }}
---
{{- if .Values.volumeMounts }}
{{- if .Values.volumeMounts.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "helmproj.fullname" . }}-vols
  namespace: {{ include "helmproj.namespace" . | quote }}
data:
  {{- range $key, $value := .Values.volumeMounts.secrets }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
{{- end }}
{{- end }}
